version: '3'

services:
  db:
    image: mariadb:11.0
    restart: always
    environment:
      MYSQL_DATABASE: fly-project
      MYSQL_USER: fly
      MYSQL_PASSWORD: project
      MYSQL_ROOT_PASSWORD: 4dm!N
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: