################### DEBUG ###################
quarkus.log.level=INFO
quarkus.log.category."org.apache.http".level=DEBUG

################### APIs ###################
# pokemon api
quarkus.rest-client.pokemon-api.url=https://pokeapi.co
quarkus.rest-client.pokemon-api.scope=javax.inject.Singleton