################### DEBUG ###################
quarkus.log.level=INFO
quarkus.log.category."org.apache.http".level=DEBUG
################### QUARKUS ###################
quarkus.http.port=8080
################### DATABASE ###################
quarkus.datasource."mariadb".devservices.port=3306
quarkus.datasource."mariadb".devservices.db-name=fly-project
quarkus.datasource."mariadb".devservices.username=brotato
quarkus.datasource."mariadb".devservices.password=root
################### APIs ###################
# pokemon api
quarkus.rest-client.pokemon-api.url=https://pokeapi.co
quarkus.rest-client.pokemon-api.scope=javax.inject.Singleton